os:
    - linux

sudo: required
dist: trusty

language: c

services:
    - docker

install:
    - sed -e 's/${CHECK_CODE}/'${CHECK_CODE}/g -e 's/${PG_VERSION}/'${PG_VERSION}/g Dockerfile.tmpl > Dockerfile
    - docker-compose build

script:
    - docker-compose run tests

env:
    - PG_VERSION=9.5 CHECK_CODE=clang
    - PG_VERSION=9.5 CHECK_CODE=false
    - PG_VERSION=9.6 CHECK_CODE=clang
    - PG_VERSION=9.6 CHECK_CODE=false
    - PG_VERSION=10  CHECK_CODE=clang
    - PG_VERSION=10  CHECK_CODE=false
